In [111]:
import numpy as np
from sklearn.datasets import load_iris
#For verification
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [99]:
iris = load_iris()
data = iris.data
target = iris.target
data.shape

(150, 4)

Testing data without PCA

In [120]:
XTrainWithout, XTestWithout, yTrainWithout, yTestWithout = train_test_split(data, target, random_state=42)
XTrainWithout.shape

(112, 4)

In [123]:
clf = GaussianNB()
clf.fit(XTrainWithout, yTrainWithout)
yPred = clf.predict(XTestWithout)
yPred == yTestWithout

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

My Implementation

In [100]:
covMat = np.cov(data.T)
covMat.shape
covMat

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [101]:
eigValues, eigVectors = np.linalg.eig(covMat)
eigVectors.shape

(4, 4)

In [102]:
# dataAfterPCA = np.matmul(eigVectors[:, :2].T, data.T).T
# dataAfterPCA.shape

WT = eigVectors[:, :2].T
dataAfterPCA = np.zeros(shape = (len(data), 2))
for i in range(len(data)):
    dataAfterPCA[i] = np.matmul(WT, data[i])

dataAfterPCA.shape

(150, 2)

In [103]:
XTrain, XTest, yTrain, yTest = train_test_split(data, target, random_state=42)
XTrain.shape, XTest.shape

((112, 4), (38, 4))

In [125]:
clf = GaussianNB()
clf.fit(XTrain, yTrain)
yPred = clf.predict(XTest)

yPred == yTest

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

Now, testing against sklearn's implementation

In [105]:
iris = load_iris()
data = iris.data
target = iris.target
data.shape

(150, 4)

In [106]:
pca = PCA(n_components=2)
pca.fit(data)
transformedData = pca.transform(data)
transformedData.shape

(150, 2)

In [107]:
XTrainSk, XTestSk, yTrainSk, yTestSk = train_test_split(transformedData, target, random_state=42)
XTrainSk.shape, XTestSk.shape

((112, 2), (38, 2))

In [126]:
clf = GaussianNB()
clf.fit(XTrainSk, yTrainSk)
yPred = clf.predict(XTestSk)

yPred == yTestSk

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])